spring:
  application:
    name: microservice-zuul-gateway
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    aigouEmployee.serviceId: EMPLOYEE-PROVIDER
    aigouEmployee.path: /employee/**  # 匹配 /xxx开头的请求映射到user-provider服务上
    #产品的服务路由:
    aigouProduct.serviceId: aigou-product
    aigouProduct.path: /product/**
  ignored-services: "*" #user-provider #忽略直接使用服务名访问  *忽略所有的
  prefix: /aigou   # 访问前缀